### ISSUE TITLE
Enhance display of Table to use Eclipse General preferences

### ISSUE THREAD

**Issue by mypsycho** [eclipse-sirius/sirius-desktop#116]
On Eclipse Photon (2018), TableViewer has been updated to support theme configuration.

Table representation uses old mechanism that decrease the quality of renderering.
Current rendering is 
<img width="1037" alt="CaptureOldVisual" src="https://github.com/eclipse-sirius/sirius-desktop/assets/823389/5ee9642c-fc65-4e0b-896f-b547c4c99665">
We can notice:
- Selected cell has black foreground with blue background which tempers the reading.
- First column (line header) and other columns has different font (Default one ie Segoe vs Arial).
- When unset in descriptor, First column and other columns have different font size (9 vs 8).

We can improve display on those 3 elements to get this rendering:
<img width="1023" alt="CaptureNewVisual" src="https://github.com/eclipse-sirius/sirius-desktop/assets/823389/639c405c-1227-43d0-886d-ccc16a552658">
- Use theme color from Eclipse when unspecified.
- Same font for all cells
- Same font size when not explicit in Table description

**Comment by lredor** [comment]
"On Eclipse Photon (2018), TableViewer has been updated to support theme configuration." --> Have you some examples in classical Eclipse UI showing these updates ?

**Comment by mypsycho** [comment]
Steps to reproduce:
- In a runtime instance, import  [TableRefresh.zip](https://github.com/eclipse-sirius/sirius-desktop/files/13265190/TableRefresh.zip).
- Make sure to use 'Classic' or 'Light' theme in Preferences.
- Open "new Model all associations"
- Notice the followings issues:
  - when moving cursor over a cell, there is no hint of the current selection. (unlike most of Eclipse widgets like 'Model Explorer' tree)
  - when clicking on a cell, the selected cell uses a dark blue color. This color is not used in the platform. As the text is still black, readability  is bad unless user increase the contrast of the screen.
  - when clicking on a cell, the other cells of the line have a dark grey background. This is also difficult to read as the foreground stays back.
  - On line 'class 2 to class 3', the first 2 cells display the same text but the display is uncomfortable as the first cell use 'Segoe' font (from Preferences > ... > Colors and Fonts) but the second cell uses 'Arial'
  - There is a glitch when changing selection. Select the cell of (AbtractClass1, Class1) then select the cell (Class4, Class3): The cell (Class4, Class1) changes color for no reason until the mouse moves again.

When applying the patch,
- All fonts are based on Preferences.
- Colors (forerground and background) of selected cells match the colors of the platform for active or inactive Editor.
