### ISSUE TITLE
Get the name of the existing images folder for ImageManager

### ISSUE THREAD

**Issue by GlennPlou** [eclipse-sirius/sirius-desktop#127]
The ImageManager should get the existing images folder if it exists and be case insensitive: if a folder is named "IMAGES" or "Images" on a project, it should be used by default instead of "images" defined in ImageManager.IMAGE_FOLDER_NAME.

See PR https://github.com/eclipse-sirius/sirius-desktop/pull/128

**Comment by scosta-obeo** [comment]
Step To Validate:

- Create a project with a diagram with a node
- Create a folder `iMaGes` in the project (with this case)
- Copy an image in your clipboard
- Paste the image on the node in the diagram
- **Expected**: no error in error log, the image has been pasted onto the node, the image is in the folder `iMaGes`.

**Comment by florianbarbin** [comment]
> Step To Validate:
> 
>     * Create a project with a diagram with a node
> 
>     * Create a folder `iMaGes` in the project (with this case)
> 
>     * Copy an image in your clipboard
> 
>     * Paste the image on the node in the diagram
> 
>     * **Expected**: no error in error log, the image has been pasted onto the node, the image is in the folder `iMaGes`.

This scenario works as expected on Linux.

**Comment by scosta-obeo** [comment]
Validated on ODCE 11.9.0.202402211421 for Windows
