### ISSUE TITLE
Add Move Pinned Elements Feature

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#141]
In diagram, I propose to add checkbox entry `Move Pinned Elements` (in the arrange toolbar menu, arrange selection toolbar menu and in `Layout` sub menu of contextual/diagram menu) to choose to layout as if no element was pinned. This feature would apply to Arrange/Arrange Selection and Arrange Linked Border Node.

**Comment by florianbarbin** [comment]
Validated by Glenn with Capella stable 19022024
