### ISSUE TITLE
Please use the latest version of guava 32.1.3.jre

### ISSUE THREAD

**Issue by merks** [eclipse-sirius/sirius-desktop#167]
https://github.com/eclipse-simrel/simrel.build/issues/80

**Comment by pcdavid** [comment]
We're on it, but see https://github.com/eclipse-sirius/sirius-desktop/pull/163#issuecomment-1815906709

**Comment by pcdavid** [comment]
Once Acceleo & EMF Compare (which we depend on) have made the move, we'll be able to re-integrate https://github.com/eclipse-sirius/sirius-desktop/commit/0e69e87df153db6f83b550eef3449e40918dfd82

**Comment by merks** [comment]
Do you know if those projects are likely to take action? 🤞

**Comment by pcdavid** [comment]
@Kellindil is supposed to look at these, hopefully today. I've poked him.

**Comment by pcdavid** [comment]
Laurent (@Kellindil) has [contributed](https://github.com/eclipse-simrel/simrel.build/commit/85317c46611f2206ccfae4de753fef71e7972891) 2 versions of Acceleo 3.7 and EMF Compare which are compatible with Guava 32.
I just launched our full test suites on [my own PR for 2023-12 compatibility](https://github.com/eclipse-sirius/sirius-desktop/pull/163) with these versions and [Guava 32 compatibility](https://github.com/eclipse-sirius/sirius-desktop/pull/163/commits/d611f30a2cfb20c2c0023ef6b61b45444b3f0ece).

I'll see tomorrow morning how that went (they take a while to run), but unless there's something really broken I'll merge that and contribute both GMF Runtime 1.16.2 (which moves to Batik 1.17) and this Sirius 7.3.0rc1 (which moves to Batik 1.17 too, and Guava 32) to the simrel.

**Comment by merks** [comment]
That sounds awesome 😎 I’m really impressed and grateful for the super rapid 🚀 contributions.

**Comment by pcdavid** [comment]
Should be fixed by e944ba164ebc1d52b892846e90067a98f022bf28.

A Sirius Desktop 7.3.0rc1 with this change has been merged to the SimRel (along with GMF Runtime 1.16.2rc1): https://github.com/eclipse-simrel/simrel.build/pull/90

The build seems green: https://ci.eclipse.org/simrel/job/simrel.build/job/main/86/

The repo analyzer job failed: https://ci.eclipse.org/simrel/job/simrel.oomph.repository-analyzer.test/2043/
It seems to be trying to find JARs from Sirius 7.2.1 (the version contributed before that commit), , but I'm not sure why:

> Failed: /home/jenkins/agent/workspace/simrel.oomph.repository-analyzer.test/report/artifacts/plugins/org.eclipse.sirius.ui.editor_7.2.1.202309051053.jar

**Comment by merks** [comment]
Great!  You're awesome! 🏅 
 
This just leaves CDO:

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/208716/96cddba4-4414-41bd-9315-5c5820ab9a71)

Don't worry about the test build thing.  If fails because the server sometimes serves stale metadata that doesn't match the actual artifacts in repository.   I just kick it again and then it's fine...
