### ISSUE TITLE
In CrossTable, Precondition or canEdit check is missing when editing a cell

### ISSUE THREAD

**Issue by mypsycho** [eclipse-sirius/sirius-desktop#168]
In CrossTable, when clicking on cell with updater or creation tool, canEdit and precondition should be tested to prevent entering edit mode if not expected.
Currently such evaluation is done only when edition is done.

**Comment by lredor** [comment]
Steps to reproduce are available in the corresponding [PR 169](https://github.com/eclipse-sirius/sirius-desktop/pull/169#issue-2005875258).
