### ISSUE TITLE
Position of synchronized nodes may be inconsistent when created in another diagram

### ISSUE THREAD

**Issue by GlennPlou** [eclipse-sirius/sirius-desktop#18]
Reproduced with OD 11-9, Sirius 7.2.0.

When synchronized nodes in one diagram are created via another diagram, the nodes that appear in the first diagram are all overlapped.

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/33932970/4a687c87-6fc0-455b-9593-022842f301be)
In this screenshot, GrayElements diagram has no synchronized elements, whereas elements in the ColoredElements diagram are all synchronized. After creating a Package and 3 Classes, they are all overlapped.

This overlapping behavior appears when the editors are side by side. When switching tabs, the behavior is different and nodes are not overlapped.
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/33932970/d629c11f-f893-41a0-87de-7f2f7fb25414)
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/33932970/b7929acf-34c7-46d6-8abf-4bb4c961e3f7)

### To reproduce:
Archive projects to reproduce bug: [overlapped.nodes.zip](https://github.com/eclipse-sirius/sirius-desktop/files/12146967/overlapped.nodes.zip)
1. Import attached projects in your workspace (`overlapped.nodes.test`, `overlapped.nodes.test.model` from `overlapped.nodes.zip` archive)
2. Open `new GrayElements` and `new ColoredElements` diagrams.
3. In `new GrayElements` diagram, create EPackages and EClasses by using the palette.
4. Switch to `new ColoredElements` diagram (or observe the result if your editors are side by side)
==> K-O nodes are overlapped.

**Comment by scosta-obeo** [comment]
Similarly, there are a number of cases where the position of nodes created (directly or indirectly) is inconsistent or non-uniform.

Here's the specification for the new behaviour:
* On the diagram background, the first element is placed in the middle, with the others to follow according to ticket preference #78.
* In a container, the first element is placed at the top left and the others follow according to ticket #78's preference.
* When the first element already has a position (tool click position, D&D position), the other unplaced elements are placed to follow according to ticket #78 preference.

**Comment by lredor** [comment]
A leak has been detected corresponding to commit https://github.com/eclipse-sirius/sirius-desktop/commit/b8a5c6a9d0888e4f26a99210f70bd247a9981c51.

Steps to reproduce:
* Launch the test `org.eclipse.sirius.tests.unit.diagram.outline.OutlineContextualMenuTest` in debug
* Add a breakpoint in `SiriusLayoutDataManagerImpl.addCreatedViewForInitPositionLayout(Diagram, LinkedHashSet<View>)` and in `SiriusLayoutDataManagerImpl.removeLayoutViews(Diagram)` 
* Observed: `SiriusLayoutDataManagerImpl.addCreatedViewForInitPositionLayout(Diagram, LinkedHashSet<View>)` is called three times and `SiriusLayoutDataManagerImpl.removeLayoutViews(Diagram)` only one. So the map `createdViewForInitPositionLayout` is not correctly cleaned.

**Comment by scosta-obeo** [comment]
Validated with ODCE 11.9.0.202402211421
