### ISSUE TITLE
Set the preference to mark moved items as pinned false by default

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#192]
Now, the preference `Automatically mark moved elements as pinned` is `true` by default. So, when the diagram layout is executed, certain elements are not moved without the user really being aware of it. As a result, the user thinks that the layout action is not working. The user is not necessarily aware of the pin feature, let alone this preference.

I propose to set this preference to `false` by default so that the user is fully aware when this preference is activated.

**Comment by florianbarbin** [comment]
Validated by Glenn with Capella stable 19022024
