### ISSUE TITLE
Moving a label is considered as a drag and drop

### ISSUE THREAD

**Issue by sdrapeau** [eclipse-sirius/sirius-desktop#193]
Steps to reproduce:
- In a diagram, select the label of a Node.
- Move the mouse to display the cross that extends in four directions.
- Move the label.
=> The move is interpreted as a drag-and-drop.
- If the mouse is released, the Node is positioned at coordinates 0,0 of the graphical container (diagram or node container).

Code to reproduce : 
[DragAndDropBorderLabelCase.zip](https://github.com/eclipse-sirius/sirius-desktop/files/13649517/DragAndDropBorderLabelCase.zip)

**Comment by lredor** [comment]
The PR #194 proposes a fix for this problem. Other analysis must be done to consider this problem has fully solved (see commit message).
