### ISSUE TITLE
Stale PMI

### ISSUE THREAD

**Issue by ewillink** [eclipse-sirius/sirius-desktop#200]
The Sirius PMI pages have entries that suggest reporting bugs via Bugzilla.

**Comment by pcdavid** [comment]
I've added proper links, but it seems like the "Report a bug" etc. buttons are hard-coded to point to bugzilla.

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/10608/ca32175b-85b8-4e0b-8403-253c95f8b718)

**Comment by ewillink** [comment]
Thanks. 

> but it seems like the "Report a bug" etc. buttons are hard-coded to point to bugzilla.

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4085 raised.
