### ISSUE TITLE
Better consider PREF_DISPLAY_VSM_USER_FIXED_COLOR_IN_PALETTE in color Palette

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-desktop#326]
We should not display the `suggested color` part in the color dialog if PREF_DISPLAY_VSM_USER_FIXED_COLOR_IN_PALETTE = false

**Comment by GlennPlou** [comment]
PR https://github.com/eclipse-sirius/sirius-desktop/pull/329 has been merged.
