### ISSUE TITLE
ELK debug traces and export only provide XML files in Temporary folder

### ISSUE THREAD

**Issue by mypsycho** [eclipse-sirius/sirius-desktop#343]
When enabling traces for ELK layout, generated files are created in a default folder.
This folder is not related to the project or the workspace and thus difficult to access.

Moreover export format is XMI but ELK online tools does not support this format directly.
User should be able to choose the file format to export or in debug trace.

**Comment by lredor** [comment]
The default folder mentioned by @mypsycho is the Java temporary folder path `java.io.tmpdir` (for example under Windows: `%USER%\AppData\Local\Temp`).

As explained by Nicolas, the export folder path is used in two cases:
* when the user explicitly exports a diagram (with contextual menu `Export diagram as ELK Graph`)
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/1825882/8edfe50d-1e04-4b67-ac20-79084200b30a)
* or during an arrange launched if an ELK Layout is selected in the VSM and the tracing option is activated for `org.eclipse.sirius.diagram.elk`.
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/1825882/e92243f3-c8b7-476e-a186-5dcd489d7779)
