### ISSUE TITLE
Wrong labels on src folder tree in a Modeling Project

### ISSUE THREAD

**Issue by vrichard12** [eclipse-sirius/sirius-desktop#368]
The labels of the src folder tree in a Modeling Project shown in the Model Explorer view are wrong.
The same is true for the "Plug-in Dependencies" tree.
See screenshot :
![ModelExplorerWrongTreeLabels](https://github.com/eclipse-sirius/sirius-desktop/assets/6783266/ec827904-8526-4955-a815-6b4e83f1258e)

Removing the modeling nature restores the correct labels.

Observed on Sirius 7.4.1.

**Comment by pcdavid** [comment]
Testing with Obeo Designer 11.8, which is based on Eclipse 4.20 / 2021-06, Sirius's `SessionLabelProvider` is never called for elements from the JDT like `PackageFragmentRoot`. Now (Eclipse 2023-03) we are called for these elements, but since we don't know anything about them we use their `toString()` value, which is designed for debugging only.

**Comment by pcdavid** [comment]
I've tested various versions of the Eclipse Modeling package:
* 2021-12: labels are OK
* 2022-03: labels are KO

**Comment by pcdavid** [comment]
Sirius 6.5.1 installed on Eclipse 2022-03: KO

So the change is somewhere in Eclipse/SWT/JFace/CNF/JDT between 2021-12 and 2022-03.

**Comment by pcdavid** [comment]
Commenting out `appearsBefore="org.eclipse.jdt.java.ui.javaContent"` on [this line](https://github.com/eclipse-sirius/sirius-desktop/blob/master/plugins/org.eclipse.sirius.ui/plugin.xml#L301) seems to fix the issue, but the impacts are not clear yet. This particular line was added a long while ago (2012) probably for good reasons at the time, and blindly removing it may break other things in subtle ways.

**Comment by vrichard12** [comment]
For the records, the Project Explorer view is also concerned.
