### ISSUE TITLE
 Container Drop tool is ignored when not defined in the same Diagram Description

### ISSUE THREAD

**Issue by mypsycho** [eclipse-sirius/sirius-desktop#380]
When defining the list of "Drop Descriptions" in a Node Description, Container Drop tool from other diagram are available but ignored at runtime.

in the code of [DDiagramElementContainerWithInterpreterOperations#getDropToolsOnActivatedLayers(...)](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/metamodel/operations/DDiagramElementContainerWithInterpreterOperations.java#L173), only default layer of current diagram description is considered. If the tool is defined in default layer of another diagram, it will not be considered.

Steps to reproduce:
- Create 2 diagrams description with a node in each one.
- Create a valid ContainerDrop in a diagram using 'model' source and make it works for the node of the same diagram.
- Add this tool in the node description of the other diagram.

=> the tool won't works because of the "getDropTools" implementation.

**Comment by lredor** [comment]
What are you waiting for?
I think that the tool, defined in `DiagA` must not be listed in the `drop descriptions` list of the node defined in `DiagB`. Indeed, it is not designed to manipulate mapping of DiagB.

Is this what you expect?

**Comment by lredor** [comment]
Here is a project to reproduce the problem described by Nicolas.
[Issue380ProjectSample.zip](https://github.com/eclipse-sirius/sirius-desktop/files/15351234/Issue380ProjectSample.zip)

**Comment by mypsycho** [comment]
> What do you expect ? I think that the tool, defined in `DiagA` must not be listed in the `drop descriptions` list of the node defined in `DiagB`. Indeed, it is not designed to manipulate mapping of DiagB.

Not listing the tool would prevent error for Specifier and misunderstanding. 

On another hand, if DropTool is the same for several diagrams, a specifier would like to **avoid copy/paste**. In this case, the list of enabled tools should be all tools from default layer (not an instance of AdditionalLayer) plus the one from additional active layers.

I think that changing the list of enabled tools offers more opportunities while being simpler.

**Comment by lredor** [comment]
After exchange with Nicolas, it appears that it will be more coherent to not change the drop descriptions listed but to have a coherent behavior with other tools (ie allow the usage of tools of another diagram). Examples : 
- For `Delete Element` tool in [`DeletionCommandBuilder.setTool()`](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/tools/internal/command/builders/DeletionCommandBuilder.java#L218), the tool is directly set according to the tool description selected for the mapping (without checking the layer in which this tool is).
- For `Direct Edit` tool in [`ToolBasedLabelDirectEditPolicy.getDirectEditTool(DMappingBased)`](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/edit/policies/ToolBasedLabelDirectEditPolicy.java#L99), the tool is directly set according to the tool description selected for the mapping (without checking the layer in which this tool is).
- For `Navigation Description` in [`OpenMenuContribution.buildOpenableRepresentationsMenu(IMenuManager, EObject, Session, EditPart, TransactionalEditingDomain)`](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/menu/OpenMenuContribution.java#L180), all selected Navigation Description are considered and filtered if they are not in an active viewpoint.
- ...

So as for the above examples, more precisely as for `Navigation Description`, all the selected drop tools wiil be considered if they are in an active viewpoint.

Technical information: For the above analysis cases, the tools are considered even if they are in a not activated optional layer. The relevance of this behavior could be questioned, but that is not the point.

**Comment by lredor** [comment]
To have a full analysis on tools visible in `Behavior` tab in Properties view of a node:
- The behavior for `Detail Descriptions` is the same as `Navigation Description` (in [`SubDiagramMenu.createDetailsActions(DDiagramElement, IMenuManager, TransactionalEditingDomain, IGraphicalEditPart)`](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/menu/SubDiagramMenu.java#L133)).
- The behavior for `Paste Descriptions` is the same as `Drop Descriptions` (in [`PasteTargetQuery.getAvailablePasteTools()`](https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/query/PasteTargetQuery.java#L62)). It will therefore also be necessary to change behavior to be consistent.
- The `Double Click Description` tool is directly set in [`DoubleClickEditPolicy.getOpenCommand(Request)`] (https://github.com/eclipse-sirius/sirius-desktop/blob/205de3b68e291c73017b68854ce6f9d76e860b97/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/edit/policies/DoubleClickEditPolicy.java#L123).

**Comment by lredor** [comment]
Steps to validate (drop description case):
- Import project `Issue380` from [Issue380ProjectSample-v2.zip](https://github.com/eclipse-sirius/sirius-desktop/files/15418986/Issue380ProjectSample-v2.zip)
- Open the diagram`mySecondDiagram`
- Drag'n'drop the class `C1` from the Model Explorer view to the diagram
- **Expected:** The class `C1` is created on the diagram.

You can also validate that the new tests added in the PR are OK.
