### ISSUE TITLE
DirectEditLabel does not provide 'view' variable during operation execution

### ISSUE THREAD

**Issue by mypsycho** [eclipse-sirius/sirius-desktop#394]
'view' variable is available when evaluating 'inputLabelExpression' before edition.
Specifier can access to decorator containment to get the text to initial edition field

But the variable is not available when performing the operation when edition is ended.

As workaround, if Specifier needs the semantic element of container, he/she can only set a side effect in inputLabelExpression query.
This lead to poor designed-code.

'view' variable should be provided.

**Comment by lredor** [comment]
The PR #395 solves the problem. It will be completed soon with an automatic test.

**Comment by lredor** [comment]
> The PR #395 solves the problem. It will be completed soon with an automatic test.

Automatic test has been added in the PR.
