### ISSUE TITLE
How to measure time cost while opening a model?

### ISSUE THREAD

**Issue by Cirtl** [eclipse-sirius/sirius-desktop#412]
Hi everyone, I am recently doing a research which requires comparing Sirius with other modeling tools from different dimensions. 
But now I have problem with how to measure the time it takes for Sirius to open a model (such as a instance of basicfamily). 
I'd appreciate it if anyone could tell me some possible methods for it.
Thank you in advance for your time and assistance.

**Comment by lredor** [comment]
Hi,
I'm not sure if this exactly meets your need, but you have some metrics offered in the "Time Profiler" view.
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/1825882/a67a1044-0426-43ef-bb20-6e267c7b7fc2)
The Sirius “Profiling” preference must be activated upstream.
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/1825882/531db507-ec34-44c7-99f1-3048c08cb31c)

**Comment by Cirtl** [comment]
Thanks a lot for your reply, I'll try it!

**Comment by pcdavid** [comment]
This is more of a question for [the discussions/forum](https://github.com/eclipse-sirius/sirius-desktop/discussions) than an issue. Closing.
