### ISSUE TITLE
How to transfer other parameters to the method that declared in my Services.java except a EObject? 

### ISSUE THREAD

**Issue by Orangewithsugar** [eclipse-sirius/sirius-desktop#435]
For Example I wanna write a method like this:
![image](https://github.com/user-attachments/assets/3ed69be9-be5a-45af-bb7a-ecf94a869a1e)
then  what should I pass in the expression?
![image](https://github.com/user-attachments/assets/53d18fd4-83ff-4c3c-a808-45d47e2675b8)
if I pass like : service:getXXX(1)
it cant call the method ....
Best Regurads!

**Comment by pcdavid** [comment]
Hi, this is a limitation of the `service:` interpreter. It's designed to be very fast/simple, and has some limitations mentioned in [the documentation](https://eclipse.dev/sirius/doc/specifier/general/Writing_Queries.html#specialized):

> The service interpreter supports parameters, but only variables can be used as parameter (no literals or complex expressions), for example: service:serviceName(view, diagram). 

It should only be used if for some reason (very rare) AQL expressions are not suitable. In your case you should probably use `aql:` expressions which do not have these limitations: `aql:self.getXXX(1)`.

**Comment by Orangewithsugar** [comment]
> Hi, this is a limitation of the `service:` interpreter. It's designed to be very fast/simple, and has some limitations mentioned in [the documentation](https://eclipse.dev/sirius/doc/specifier/general/Writing_Queries.html#specialized):
> 
> > The service interpreter supports parameters, but only variables can be used as parameter (no literals or complex expressions), for example: service:serviceName(view, diagram).
> 
> It should only be used if for some reason (very rare) AQL expressions are not suitable. In your case you should probably use `aql:` expressions which do not have these limitations: `aql:self.getXXX(1)`.

So I should write the getXXX() method in self's corresponding class instead of Service.java?

**Comment by pcdavid** [comment]
No, the receiver of a service invocation in an AQL expression ("self" in "aql:self.getXXX()") will be passed as the first parameter of your Java service method ("int getXXX(EObject self, int x)"). See [this other section of the documentation](https://eclipse.dev/sirius/doc/specifier/general/Writing_Queries.html#service_methods) for more details.

**Comment by Orangewithsugar** [comment]
Great! Thanks for taking time help~  Really appreciate!
