### ISSUE TITLE
Provide an UI feature to reset WorkspaceImage style

### ISSUE THREAD

**Issue by GlennPlou** [eclipse-sirius/sirius-desktop#471]
### Issue description

It is currently difficult and not ergonomic to delete the image associated with a node in a diagram. Today, there are 2 ways of doing this:
- Click on the “Reset style properties to default values” button, which resets all other modified features (label, color...) 
![image](https://github.com/user-attachments/assets/181c60b4-984a-4362-ad74-4ca8b3d640f9)

- Use the “Style” tab of the Properties view, and manually delete the contents of Workspace Path, then delete “workspacePath” from the Custom Feature list, and finally refresh the diagram. This method isn't ergonomic and isn't accessible to all users.
![image](https://github.com/user-attachments/assets/ac3d4d90-c2f2-4c4f-83bc-6542d779b75f)

A more ergonomic way of deleting an image associated with a node should be provided.
Since there's already a dialog for managing the image associated with a node, it would be more efficient to add functionality to the dialog rather than adding yet another context menu or toolbar button.

I propose the following change to solve the described issue: A new “Reset Image Style” button in the dialog.
![image](https://github.com/user-attachments/assets/71e62acb-38b0-460d-946b-ae79db957f5e)

### Steps to validate:

1. Import project `issue_471` in your workspace from [issue_471.zip](https://github.com/user-attachments/files/17202764/issue_471.zip), open `issue_471 package entities` diagram, select `NewEclass1`, open `Properties` view and the `Error Log` view.
![image](https://github.com/user-attachments/assets/adf79227-f2a6-4257-b07e-7dec5ad39187)
2. Click on `Set style to workspace image` button from tabbar or `Appearance `tab in `Properties` view
**Expected:** The dialog appears. The image path field refers to the actual image `issue_471/images/green_beetle.png`. The "Reset Image Style" button is enabled. "OK" button is disabled.
![image](https://github.com/user-attachments/assets/43560b03-bfbd-4dc4-8fc5-d2d67de6dd0a)
3. Click on "Reset Image Style" button.
**Expected:** The "Reset Image Style" button is disabled. OK button is enabled. the path is empty.
4. Select another image in the gallery, such as "blue_beetle.png" in issue_471 > images.
**Expected:** The path refers to `issue_471/images/blue_beetle.png`. The "Reset Image Style" button is enabled. "OK" button is disabled.
5. Click on an invalid location, such as an empty place in the gallery, or the project "issue_471" in the tree viewer.
**Expected:** The path is updated with the actual Workspace Image `issue_471/images/green_beetle.png`. The "Reset Image Style" button is enabled. "OK" button is disabled.
6. Click on "Reset Image Style" button again, then click "OK".
**Expected:** The style of the node has been updated: the image is not even used, and other custom features are preserved (bold, italic, color label, size label...)
![image](https://github.com/user-attachments/assets/5c7839e3-1269-4303-8c0d-8d782dade48d)

**Comment by SteveMonnier** [comment]
[issue_471_updated.zip](https://github.com/user-attachments/files/18172299/issue_471_updated.zip)
Validated with OD 11.9.1 but I had to change the version number in the aird file and recreate the diagram.
