### ISSUE TITLE
Adapt the size of created Nodes according to their label size.

### ISSUE THREAD

**Issue by GlennPlou** [eclipse-sirius/sirius-desktop#65]
By using the auto-size value "-1" in the odesign, the Container size adapts to the label size automatically if the container is not manually resized. It should be possible to provide similar behavior for Nodes.

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/33932970/c2ee916a-20bc-45af-9407-b2514dd6e9b4)
* Here, for the container, `-1` value has been set for `Width Computation Expression` and `Height Computation Expression`. It is created with a default size (150/70 defined in `oes.diagram.ui.tools.api.layout.LayoutUtils.DEFAULT_CONTAINER_DIMENSION`) which is sufficient for the label to be correctly displayed in most cases, otherwise the size of the container increases with the size of the label.
* In contrast, for the node, using the `-1` value in  `Size Computation Expression`, the default node size is 20/20 (defined in `oes.diagram.ui.business.internal.query.DNodeQuery.DEFAULT_NODE_DIMENSION`), which is not sufficient to display the label correctly. Furthermore, the size of the node does not adapt to the size of the label.

I attach a sample to reproduce the issue: [autosized.nodes.test.zip](https://github.com/eclipse-sirius/sirius-desktop/files/12334790/autosized.nodes.test.zip)

1. Import both projects `autosized.nodes.test.model` and `autosized.nodes.test` in your workspace
2. Open `new GrayElements` diagram from `autosized.nodes.test.model/representation.aird/MyViewpoint/GrayElements`
3. Create a new EPackage using the palette ==> The label is properly displayed.
4. Create a new EClass using the palette ==> *K-O*: The label is not properly displayed.

The diagram has also been created with an EClass which has a GMF size -1/-1. It is displayed has 10/10 and the label is still not properly displayed.
Note that the "AutoSize" button in the toolbar properly sizes the node according to the label.
Useful code reference: `oes.ext.gmf.runtime.gef.ui.figures.SiriusWrapLabel.getPreferredSize(int, int)`

See PR #28

**Comment by GlennPlou** [comment]
This issue is resolved, see PR #28, #227, #229, #232.

**Comment by scosta-obeo** [comment]
it doesn't work: see initial step to reproduce

**Comment by pcdavid** [comment]
After some exchanges, the initial steps to reproduce are not up to date with the final design/implementation.
As mentioned in the released notes, for square nodes it's not the `sizeComputationExpression` that should be set to -1 to enable auto-size, but both widh and height:

> The SquareDescription can now have -1 value for height and width. If the value -1 is used for both width and height enable the "auto-size" mode.

With this configuration:
![Capture d’écran du 2024-03-01 10-38-29](https://github.com/eclipse-sirius/sirius-desktop/assets/10608/9bda3961-9084-46c5-9a3b-deb8a83aafed)

a newly created node gets a size adapted to its internal label:

[Capture vidéo du 2024-03-01 10-47-00.webm](https://github.com/eclipse-sirius/sirius-desktop/assets/10608/0c58c440-557e-43a4-a4b7-4a159afae95a)
