### ISSUE TITLE
Provide a way to access to all tools contained in Diagram inner Toolbar when Diagram size is reduced

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#81]
In Sirius diagram, when user reduces diagram width, in the diagram toolbar, the latest tools are hidden and not accessible.

_migrated from bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=582149_

**Comment by scosta-obeo** [comment]
Step to validate:
- Open a diagram
- Resizes the window so that there is no longer enough space in the diagram toolbar to display all tools
**Expected**: the tool items that are not visible on the first line are visible on the second/third... line (for windows) or in sub menu (for linux)

**Comment by GlennPlou** [comment]
Validated with OD 11.9 stable 20240221. Sirius 7.4.0.
