### ISSUE TITLE
Disconnected "Note Attachment" can appear when linked to an edge

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#82]
In Sirius diagram, in some case the note attachment still alive or visible without source or target.

Scenario 1, step to reproduce:
- Import attached project [bug82](https://github.com/eclipse-sirius/sirius-desktop/files/12409340/bug82.zip)
- Open diagram bug82
- Remove Note1
- **Expected:** Note1, note attachment of Note1, note attachment of Note2 and, if preference "Remove/Hide note when the annotated element is remove/hidden" is enable, Note2 are removed.
- **Observed:** Note1 and note attachment of Note1 is removed but the note attachment of Note2 still here, connected between Note2 and nothing.

Scenario 2, step to reproduce:
- Import attached project [bug82](https://github.com/eclipse-sirius/sirius-desktop/files/12409340/bug82.zip)
- Open diagram bug82
- Enable preference "Remove/Hide note when the annotated element is remove/hidden"
- Hide edge Ref
- **Expected:** Ref, all notes and notes attachment are hidden.
- **Observed:** Note2 and the note attachment of Note2 still visible, connected between Note2 and nothing.

Scenario 3, step to reproduce:
- Import attached project [bug82](https://github.com/eclipse-sirius/sirius-desktop/files/12409340/bug82.zip)
- Open diagram bug82
- Disable preference "Remove/Hide note when the annotated element is remove/hidden"
- Hide edge Ref
- **Expected:** Ref and all notes attachment are hidden.
- **Observed:** All note attachment still visible.

**Comment by GlennPlou** [comment]
Validated with OD 11.9 stable 20240221. Sirius 7.4.0.
