### ISSUE TITLE
Edge can be created twice by Creation Tools

### ISSUE THREAD

**Issue by helloworld-at-github** [eclipse-sirius/sirius-desktop#85]
Scenario: 
- I would like to create edge between two nodes from both sides, namely starting to create edge from any side to the other.
- I have created two relation based edges for each creation direction from either of the two nodes, just by switching the source mapping and target mapping.
- During test, I have just defined one Edge Creation Tool for one of the Edge Mappings.
- But by testing in my model, each time when I tried to create one edge through the Edge Creation Tool, two edges were created, which seem to map the two Edges defined in odesign file. But this doesn't make any sense to me, since only one edge has been given in the edge mapping for the Edge Creation Tool.

Used version:
- Obeo Designer Community 11.8

Screenshots:
- two relation based edges in odesign file：
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/8917905/76aa5342-bc98-4d36-a8ec-7f23c054dad0)

- one Edge Creation Tool:
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/8917905/3bbe9278-e9af-44cb-b041-6b74c8e6b6dc)

- model:
![image](https://github.com/eclipse-sirius/sirius-desktop/assets/8917905/b5124ca1-afa4-4352-be09-4dfd89da5d0f)

Expected behavior:
- Only the given edge Mapping will be created through the Edge Creation Tool.

**Comment by pcdavid** [comment]
Hi,

I understand that this can be confusing, but in this case it actually works as designed.
For synchronized mappings (the default),  which graphical elements are created (or not) on the diagram depends only on the state of the underlying semantic model, *not* the tools that have been invoked by the user.

In your case, the tool put the model in a state which matches both edge mappings, so both are created.

The fact that the _Edge Creation Tool_ is associated to a particular edge mapping (and not the other) actually only means that this particular tool will be available between the source and target mappings of the edge. It does not imply by itself that the tool will create an instance of this edge. It's a little confusing at first, but it's also the source of a lot of the power & flexibiliy of Sirius: the system does not make any assumptions about the effect a given tool will have on the underlying model, it simply ensures that the effect of the tool, whatever it is, is reflected in the diagram afterwards (by applying the rules you defined).

It's possible to get the behavior you want. You'll need to make your edge mappings _Not synchronized_ (see the "Synchronization" section in [the reference documentation](https://eclipse.dev/sirius/doc/specifier/diagrams/Diagrams.html#graphical_elements)). In this mode, graphical instances (here edges) are never automatically created by Sirius itself, even if the semantic model is in a state that would allow them. Then it's up to you, in your various tools, to ask for their creation when relevant using the [_Create View_ and _Create Edge View_](https://eclipse.dev/sirius/doc/specifier/general/Model_Operations.html#representations) operations.
