### ISSUE TITLE
Control action leads to Deadlock

### ISSUE THREAD

**Issue by mPorhel** [eclipse-sirius/sirius-desktop#89]
Discovered with 
* Sirius - 7.2.0
* Eclipse Platform - 4.27 (2023-03)
* EMF - 2.33.0.v20230226-0921
* Ecore Tools 3.4.0
* Java : temurin-17.jdk

Issue reproduced on macOS and Win 11.

Behavior is ok with ObeoDesigner Community 11.8 (2021-03, Sirisu 

Steps to reproduce
- Preparation
  - Create an Ecore Modeling Project
  - In the opened diagvram,add a child package, 4 EClass (2 in each package)
  - Create a new diagram on the second package
  - alt: open the attached sample 
- Clic on the second package and launch the Control... action
- Deadlock : no possible click in the representation selection popup, nor cancel, nor finish

I also get the deadlock when I launch the SWTBot tests:
* `org.eclipse.sirius.tests.swtbot.LockedRepresentationContainerTest.testControlSemanticModel()`
* `org.eclipse.sirius.tests.swtbot.ControlUncontrolWithOpenedRepresentationTest`

**Comment by mPorhel** [comment]
[TestControl.zip](https://github.com/eclipse-sirius/sirius-desktop/files/12464764/TestControl.zip)

**Comment by mPorhel** [comment]
Area to investigate : 
* Shell / Active shell management in 
  * `org.eclipse.sirius.ui.tools.api.control.SiriusControlHandler`
  * 'org.eclipse.sirius.ui.tools.internal.actions.control.DesignerControlAction'

**Comment by mPorhel** [comment]
With provided patch set : tests are fine on macOS and behavior at runtime is also deadlock free.

**Comment by pcdavid** [comment]
I can review...if there's a PR.
