### ISSUE TITLE
Allow the image paste on nodes in diagram from clipboard

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#9]
Add functionality to paste an image from the clipboard onto a node or container as a workspace image style.

Scenario:

- open a diagram
- copy an image in the clipboard
- select a node in the diagram
- paste
- **Expected**:
- the image is displayed for the node
- an image is created either in the workspace

**Comment by lfasani** [comment]
Validated with ODCE 20240212
