### ISSUE TITLE
The reset style button is disabled on edges even if the font format changes

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#91]
In Sirius diagram, the reset style button is disabled on edges even if the font format (bold, italic, underline and strike through) changes.

Step to reproduce:
- Open the attached project `bugResetStyleEdge`
- Open the diagram `new testLabelEdgeDiagram`
- Select the edge or any of its labels (`BEGIN`, `CENTER` or `END`)
- Enable bold or italic
- **Expected**: the reset style button is enabled
- **Actual**: the reset style button is disabled

Attachment: [bugResetStyleEdge.zip](https://github.com/eclipse-sirius/sirius-desktop/files/12484857/bugResetStyleEdge.zip)

**Comment by GlennPlou** [comment]
Validated with OD 11.9 stable 20240221. Sirius 7.4.0.
